#!/usr/bin/perl
# Copyright (C) 2014 Tony Crisci <tony@dubstepdish.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Requires playerctl binary to be in your path (except cmus)
# See: https://github.com/acrisci/playerctl

# Set instance=NAME in the i3blocks configuration to specify a music player
# (playerctl will attempt to connect to org.mpris.MediaPlayer2.[NAME] on your
# DBus session).

use Env qw(BLOCK_INSTANCE);

my @metadata = ();
my @alt_data = "";
my $player_arg = "";

# try cmus first
my @cmus = split /^/, qx(cmus-remote -Q);
foreach my $line (@cmus) {
  my @data = split /\s/, $line;
  my @first = shift @data;
  print(@first);
  print("\n");
  print($line);
  print("\n");
  if (@first eq 'tag') {
    my $key = shift @data;
    my $value = join ' ', @data;

    @metadata[0] = $value if $key eq 'artist';
    @metadata[1] = $value if $key eq 'title';
  } elsif (@first eq 'file') {
    print("ajks");
    my $array = split /\//, $line;
    @alt_data = $array[-1];
    print(@alt_data);
  }
}

if (@metadata) {
  # metadata found so we are done
  print(join ' - ', @metadata);
  exit 0;
} else {
  print(@alt_data);
}
